initial LTI documentation
MarkUsProject/Wiki pull request #164
Opened 2022-10-11 17:29 UTC by pretendWhale

Wiki updates for https://github.com/MarkUsProject/Markus/pull/6156

2022-10-11 18:22 UTC, mishaschwartz requested changes

2022-10-11 18:22 UTC, mishaschwartz commented on Learning-Tools-Interoperability.md
> +MarkUs integrates with other Learning Management Systems via the LTI standard.
Introduce the LMS acronym here: 

```
MarkUs integrates with other Learning Management Systems (LMS) via  ...
```

2022-10-11 18:22 UTC, mishaschwartz commented on Learning-Tools-Interoperability.md
> +course based on the Canvas course information with you as an instructor.
I thought we were preventing instructors from creating new courses (as determined by policies)

2022-10-11 18:22 UTC, mishaschwartz commented on Learning-Tools-Interoperability.md
> +## For Instructors
Everything below here is canvas specific. Add a section for "Canvas" and include these instructions under that section heading. As we add support for other LMS we can add new sections.

2022-10-11 18:22 UTC, mishaschwartz commented on Learning-Tools-Interoperability.md
> +Once MarkUs is configured with your LMS, an association between your
You use LMS and Canvas interchangeably. Please make sure that we're only referring to Canvas in these sections not LMS in general

2023-06-11 19:16 UTC, david-yz-liu commented on Learning-Tools-Interoperability.md
> +MarkUs can be added via a configuration URL. The configuration URL is available at  /lti_deployments/get_canvas_config
You should elaborate this section by referring to which specific part of the Canvas documentation is relevant. For example, a search for the phrase "configuration URL" on the Canvas documentation doesn't yield any hits.

2023-06-11 19:16 UTC, david-yz-liu commented on Learning-Tools-Interoperability.md
> +the associations can be viewed on the course settings page. On this page you can manually trigger a roster synchronization,
capitalize "Course Settings" and provide a screenshot

2023-06-11 19:16 UTC, david-yz-liu commented on Learning-Tools-Interoperability.md
> +> administrators (not students)
This sentence should end with a period

2023-06-11 19:16 UTC, david-yz-liu commented on Learning-Tools-Interoperability.md
> +you may click 'create new course', which will create a new
"Create New Course" should be capitalized. Also this would be a good place for a screenshot.

2023-06-11 19:16 UTC, david-yz-liu commented on Learning-Tools-Interoperability.md
> +a list of MarkUs courses to choose from. Select the course that matches your Canvas
you should clarify that the list of MarkUs courses that appear are ones where the user is an instructor

2023-06-11 19:16 UTC, david-yz-liu commented on Learning-Tools-Interoperability.md
> +A roster sync can also be triggered manually on the course settings page.
again, "Course Settings" should be capitalized

2023-06-12 22:56 UTC, david-yz-liu approved these changes

2023-06-12 22:56 UTC, merged