add description of new bulk collection options
MarkUsProject/Wiki pull request #168
Opened 2022-11-17 21:17 UTC by pretendWhale

Adds description of new bulk collection options created in https://github.com/MarkUsProject/Markus/pull/6341

2022-11-18 19:18 UTC, pretendWhale commented
Thanks - those are great changes. One minor thing I was a little bit ambivalent about:

I added a note that the 'collect recent submissions' box can be used to collect before the due date. I think this probably makes sense given the 'default' behavior prevents early collection, and the modal text doesn't make it obvious, but I'm not sure I love the wording I used (and maybe I'm wrong and it isn't needed!). What do you think?

2022-11-21 13:11 UTC, mishaschwartz approved these changes

2022-11-21 13:19 UTC, mishaschwartz commented
@pretendWhale I think that the wording is fine for the "collect recent submissions" checkbox. I think that it's important to make it clear that submissions can now be collected before the due date. 

The only thing that I might change is instead of referring to due date/grace period, we could refer to the "due date plus any additional late submission penalty period" (or maybe something a little less wordy if you can). The only reason is that we only really use the term "grace period" to refer to the policy that removes grace credits, not the other late submission policies.

In fact, it might just be fine to change it to "due date" without any reference to the extra time since that seems to be what we're doing elsewhere in the wiki.

2022-12-14 17:20 UTC, david-yz-liu reviewed
@pretendWhale sorry I forgot to mention this, but please update the description and screenshot with the updated UI options

2022-12-14 18:38 UTC, mishaschwartz requested changes

2022-12-14 18:38 UTC, mishaschwartz commented on Instructor-Guide--Assignments--Marking--Set-Up.md
> -3. **Apply Late Penalty** - this box is checked by default. If it is unchecked, MarkUs will not apply penalties or deduct grace credits for submissions created after the due date.
This is still an option that needs to be described. It only shows up if collecting most recent, so please explain that as well in your description. 

Also, please include a screenshot of what the modal looks like with this options visible

2022-12-14 19:04 UTC, mishaschwartz approved these changes

2022-12-14 19:04 UTC, merged